app = "cartezcash"

[build]
image = "registry.fly.io/cartezcash:latest"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "11155111"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0xCC07363a51c26EFB3945192D13C7Ac95F5eb199B"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "5701364"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0xAaFF6Cb0D2FE39083bd0b2f36e31caA85B4bbF3E"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0xA9B08d0249eF14775C532654C78D40640FeA94Fd"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "3963384"
CARTESI_EPOCH_DURATION = "86400"