app = "cartezcash-fullnode"

[build]
dockerfile = "fullnode.Dockerfile"

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [services.ports.tls_options]
    alpn = ["h2"]

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
GRPC_SERVER_URL="[::1]:50051"
ROLLUP_HTTP_SERVER_URL="https://cartezcash.internal/graphql"
