[package]
name = "tower-cartesi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
ethereum-types = "0.14.1"
hyper = { version = "0.14", features = ["http1", "runtime", "client"] }
tower = "0.4.13"
